spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/mystore
    username: mystore_user
    password: mystore_password
    pool:
      enabled: true                               # Включение пула соединений
      initial-size: 10                            # Начальное количество соединений в пуле
      max-size: 50                                # Максимальное количество соединений
      max-idle-time: 30s                          # Время бездействия соединения перед закрытием
      max-life-time: 10m                          # Максимальное время жизни соединения
      validation-query: SELECT 1                  # SQL-запрос для проверки работоспособности соединения
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  thymeleaf:
    encoding: UTF-8
#  sql:
#    init.mode: always

application:
  userId: 1
  itemsPerLine: 3
  redis:
    ttlInMinutes: 1
