spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mystore
    username: mystore_user
    password: mystore_password
    driver: org.postgresql.Driver
  sql:
    init.mode: always
  jpa:
    hibernate.ddl-auto: none
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    context-path: /mystore

application:
  userId: 1
  itemsPerLine: 3
