openapi: 3.0.3
info:
  title: Payment Service API
  description: API for retrieving user payment balances.
  version: 1.0.0
servers:
  - url: http://localhost:8081
    description: Local development server

paths:
  /balance/{userId}:
    get:
      summary: Get user balance
      description: Returns the current balance for a given user.
      operationId: getUserBalance
      parameters:
        - name: userId
          in: path
          required: true
          description: Unique identifier of the user
          schema:
            type: string
      responses:
        '200':
          description: Successful response with balance
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
                    example: "12345"
                  balance:
                    type: number
                    format: double
                    example: 250.75
        '400':
          description: Invalid userId supplied
        '404':
          description: User not found
        '500':
          description: Internal server error
